functionsDirectory = "C:\\nzmobileautos\\netlify\\functions"
functionsDirectoryOrigin = "default"
redirectsOrigin = "config"
headers = []

[build]
publish = "C:\\nzmobileautos\\.next"
publishOrigin = "config"
commandOrigin = "config"
command = "pnpm build"
functions = "C:\\nzmobileautos\\netlify\\functions"

[build.environment]
NODE_VERSION = "20"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]
included_files = ["motorweb.p12"]

[[plugins]]
origin = "config"
package = "@netlify/plugin-nextjs"

[plugins.inputs]

[[redirects]]
from = "/booking"
to = "/book"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/booking/"
to = "/book"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]