[build]
  command = "pnpm build"
  publish = ".next"

[functions]
  included_files = ["motorweb.p12"]

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/booking"
  to = "/book"
  status = 301
  force = true

[[redirects]]
  from = "/booking/"
  to = "/book"
  status = 301
  force = true
